version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-containerr
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etron_dosi
    volumes:
      - ./mysqll-dataa:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - myetronnetwork

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-containerr
    ports:
      - "8086:8086"
    networks:
      - myetronnetwork
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/etron_dosi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  myetronnetwork:
